instrument_servers:
  local1:
    # ip address / domain name of the instrument server
    ip: 'localhost'
    # port the instrument server is on
    port: 5556

# address of the mongodb server
mongodb_addr: 'mongodb://localhost:27017/'

# experiment (spyrelets) list - the syntax is:
# name:
#   file: 'path/to/file.py' (can be absolute or relative to this config)
#   class: 'SpyreletClass'
#   device_aliases: {sg1: 'local_inserv1/fake_sg',
#                   osc1: 'local_inserv1/fake_osc'} }
#   [optional] spyrelets: {'sub1': 'sub_spyrelet1', ...}
#   [optional] args: 'Other arguments'
spyrelets:
  s2:
    file: '../spyrelet/examples/test_spyrelets.py'
    class: 'SubSpyrelet'
    device_aliases: {sg: 'local1/fake_tcpip_sg'}
    spyrelets: {}
    args: []
    kwargs: {}

  my_exp:
    file: '../spyrelet/examples/test_spyrelets.py'
    class: 'MyExperiment'
    device_aliases:
      sg: 'local1/fake_tcpip_sg'
      osc: 'local1/fake_osc'
    spyrelets: {s2: 's2'}
    args: []
    kwargs: {}
